name: adplatform_flutter_sdk
description: AdPlatform Flutter SDK for displaying ads in Flutter applications
version: 1.0.0
homepage: https://github.com/adplatform/flutter-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.adplatform.flutter_sdk
        pluginClass: AdplatformFlutterSdkPlugin
      ios:
        pluginClass: AdplatformFlutterSdkPlugin
