name: adnova_flutter_sdk
description: AdNova Flutter SDK - Display banner, interstitial, rewarded and native ads in your Flutter apps. Easy integration with callbacks.
version: 1.0.3
homepage: https://adnova.bbs.tr
repository: https://github.com/onvvjnmng-design/adplatform-flutter-sdk
issue_tracker: https://github.com/onvvjnmng-design/adplatform-flutter-sdk/issues

topics:
  - ads
  - advertising
  - monetization
  - banner-ads
  - rewarded-ads

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

